[program:chromium]
command=/usr/bin/chromium --no-sandbox --disable-dev-shm-usage --start-maximized https://finviz.com/screener.ashx?v=152&f=sector_tech
autostart=%(ENV_AUTO_START_BROWSER)s
autorestart=true
startretries=3
stdout_logfile=/var/log/chromium.log
stderr_logfile=/var/log/chromium.err.log
user=root
