[program:chromedriver]
command=/usr/local/bin/chromedriver --port=9515 --whitelisted-ips=0.0.0.0
directory=/usr/local/bin
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/chromedriver.log
stderr_logfile=/var/log/supervisor/chromedriver_error.log
user=root
